// <auto-generated />
namespace ProductServer.Migrations.ProductMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixDatatype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixDatatype));
        
        string IMigrationMetadata.Id
        {
            get { return "201803172055294_Fix Datatype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
